version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /pkg/otlp/metrics
      - /pkg/otlp/attributes
      - /pkg/quantile
      - /pkg/internal/sketchtest
      - /pkg/inframetadata
      - /pkg/otlp/logs
    labels:
      - dependencies
    schedule:
      interval: weekly
    ignore:
      # Ignore internal modules
      - dependency-name: github.com/DataDog/opentelemetry-mapping-go/*
    open-pull-requests-limit: 100
  - package-ecosystem: gomod 
    directory: /internal/tools
    labels:
      - dependencies
    schedule:
      interval: monthly
  - package-ecosystem: gomod 
    directory: /internal/tools/generate-license-file
    labels:
      - dependencies
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "monthly"
