version: 2
updates:
  - package-ecosystem: gomod
    directory: /pkg/otlp/metrics
    labels:
      - dependencies
    schedule:
      interval: weekly
    ignore:
      # Ignore internal modules
      - dependency-name: github.com/DataDog/opentelemetry-mapping-go/*
  - package-ecosystem: gomod
    directory: /pkg/otlp/attributes
    labels:
      - dependencies
    ignore:
      # Ignore internal modules
      - dependency-name: github.com/DataDog/opentelemetry-mapping-go/*
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /pkg/quantile
    labels:
      - dependencies
    ignore:
      # Ignore internal modules
      - dependency-name: github.com/DataDog/opentelemetry-mapping-go/*
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
  - package-ecosystem: gomod
    directory: /pkg/internal/sketchtest
    labels:
      - dependencies
    ignore:
      # Ignore internal modules
      - dependency-name: github.com/DataDog/opentelemetry-mapping-go/*
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
  - package-ecosystem: gomod 
    directory: /internal/tools
    labels:
      - dependencies
    schedule:
      interval: monthly
  - package-ecosystem: gomod 
    directory: /internal/tools/generate-license-file
    labels:
      - dependencies
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "monthly"
