# this file contains overrides for the automatic determination of copyright
# implemented in tasks/licenses.py.  The table keys are the golang package name
# or pattern, and the value is either a copyright owner or a list of owners.
#
# Package patterns may end with a `*`.  When multiple patterns match, the longer
# is preferred.
#
# Copyright statements should reflect the copyright exactly as it is shown on
# the original component.

go.opentelemetry.io/*: Copyright The OpenTelemetry Authors
contrib.go.opencensus.io/*: Copyright 2017, OpenCensus Authors
google.golang.org/genproto/*: Copyright 2020 Google LLC
github.com/DataDog/opentelemetry-mapping-go/*: Copyright [2023-Present] Datadog, Inc.
github.com/modern-go/concurrent: Copyright (c) 2018 Tao Wen
github.com/modern-go/reflect2: Copyright (c) 2018 Tao Wen
github.com/go-logr/logr: "Copyright 2019 The logr Authors."
github.com/go-logr/stdr: "Copyright 2019 The logr Authors."
github.com/golang/groupcache: Copyright 2012 Google Inc.
