issues:
  # Do not limit the number of issues per linter.
  max-issues-per-linter: 0

  # Do not limit the number of times a same issue is reported.
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: '(.+)_test\.go'
      linters:
        - errcheck
    - text: "appendAssign"
      linters: gocritic

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - errcheck
    - errorlint
    - exportloopref
    - gofmt
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - tenv
    - unconvert 
    - unparam
    - unused

linters-settings:
  depguard:
    include-go-root: true
    packages-with-error-message:
      - sync/atomic: "Use go.uber.org/atomic instead"
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/DataDog/datadog-agent
          - github.com/DataDog/datadog-api-client-go
          - github.com/DataDog/opentelemetry-mapping-go
          - github.com/DataDog/sketches-go
          - github.com/dustin/go-humanize
          - github.com/golang
          - github.com/lightstep/go-expohisto
          - github.com/patrickmn/go-cache
          - github.com/stretchr/testify
          - google.golang.org/protobuf/proto
          - golang.org/x/exp
          - gopkg.in/yaml.v3
          - go.uber.org
          
  staticcheck:
    go: "1.20"
    checks: ["all",
             "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", # These ones are disabled by default on staticcheck
             "-ST1013", # Use HTTP code enums instead of integers
             "-SA1019", "-SA4011", "-SA4031" # Disabling these to re-enable golanci-lint default tests
             ]
  gofmt:
    simplify: true
  
  govet:
    check-shadowing: true

  revive:
    rules:
      - name: package-comments
        disabled: true
