// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package attributes

import semconv127 "go.opentelemetry.io/otel/semconv/v1.27.0"

var ExpectedDatadogAttributesMap = map[string]string{
	KeyEnv:                       "test-datadog-env",
	KeyService:                   "test-datadog-service",
	KeyVersion:                   "test-datadog-version",
	KeyArchitecture:              "test-datadog-architecture",
	KeyChronosJob:                "test-datadog-chronos-job",
	KeyChronosJobOwner:           "test-datadog-chronos-job-owner",
	KeyClusterName:               "test-datadog-cluster-name",
	KeyDDRemoteConfigID:          "test-datadog-dd-remote-config-id",
	KeyDDRemoteConfigRev:         "test-datadog-dd-remote-config-rev",
	KeyDisplayContainerName:      "test-datadog-display-container-name",
	KeyDockerImage:               "test-datadog-docker-image",
	KeyGitCommitSHA:              "test-datadog-git-commit-sha",
	KeyGitRepositoryURL:          "test-datadog-git-repository-url",
	KeyImageID:                   "test-datadog-image-id",
	KeyContainerID:               "test-datadog-container-id",
	KeyContainerName:             "test-datadog-container-name",
	KeyImageName:                 "test-datadog-image-name",
	KeyImageTag:                  "test-datadog-image-tag",
	KeyRuntime:                   "test-datadog-runtime",
	KeyCloudProvider:             "test-datadog-cloud-provider",
	KeyRegion:                    "test-datadog-region",
	KeyAvailabilityZone:          "test-datadog-zone",
	KeyTaskFamily:                "test-datadog-task-family",
	KeyTaskARN:                   "test-datadog-task-arn",
	KeyECSClusterName:            "test-datadog-ecs-cluster-name",
	KeyECSContainerName:          "test-datadog-ecs-container-name",
	KeyKubeContainerName:         "test-datadog-kube-container-name",
	KeyKubeClusterName:           "test-datadog-kube-cluster-name",
	KeyKubeDeployment:            "test-datadog-kube-deployment",
	KeyKubeReplicaSet:            "test-datadog-kube-replica-set",
	KeyKubeStatefulSet:           "test-datadog-kube-stateful-set",
	KeyKubeDaemonSet:             "test-datadog-kube-daemon-set",
	KeyKubeJob:                   "test-datadog-kube-job",
	KeyKubeCronJob:               "test-datadog-kube-cronjob",
	KeyKubeNamespace:             "test-datadog-kube-namespace",
	KeyPodName:                   "test-datadog-pod-name",
	KeyKubeAppName:               "test-datadog-kube-app-name",
	KeyKubeAppInstance:           "test-datadog-kube-app-instance",
	KeyKubeAppVersion:            "test-datadog-kube-app-version",
	KeyKubeAppComponent:          "test-datadog-kube-app-component",
	KeyKubeAppPartOf:             "test-datadog-kube-app-part-of",
	KeyKubeAppManagedBy:          "test-datadog-kube-app-managed-by",
	KeyKubeOwnerRefKind:          "test-datadog-kube-ownerref-kind",
	KeyKubeOwnerRefName:          "test-datadog-kube-ownerref-name",
	KeyKubePriorityClass:         "test-datadog-kube-priority-class",
	KeyKubeQOS:                   "test-datadog-kube-qos",
	KeyKubeReplicationController: "test-datadog-kube-replication-controller",
	KeyKubeService:               "test-datadog-kube-service",
	KeyLanguage:                  "test-datadog-language",
	KeyMarathonApp:               "test-datadog-marathon-app",
	KeyMesosTask:                 "test-datadog-mesos-task",
	KeyNomadDC:                   "test-datadog-nomad-dc",
	KeyNomadGroup:                "test-datadog-nomad-group",
	KeyNomadJob:                  "test-datadog-nomad-job",
	KeyNomadNamespace:            "test-datadog-nomad-namespace",
	KeyNomadTask:                 "test-datadog-nomad-task",
	KeyOshiftDeployment:          "test-datadog-oshift-deployment",
	KeyOshiftDeploymentConfig:    "test-datadog-oshift-deployment-config",
	KeyOSName:                    "test-datadog-os-name",
	KeyOSVersion:                 "test-datadog-os-version",
	KeyPersistentVolumeClaim:     "test-datadog-persistentvolumeclaim",
	KeyPodPhase:                  "test-datadog-pod-phase",
	KeyRancherContainer:          "test-datadog-rancher-container",
	KeyRancherService:            "test-datadog-rancher-service",
	KeyRancherStack:              "test-datadog-rancher-stack",
	KeyShortImage:                "test-datadog-short-image",
	KeySwarmNamespace:            "test-datadog-swarm-namespace",
	KeySwarmService:              "test-datadog-swarm-service",
	KeyTaskName:                  "test-datadog-task-name",
	KeyTaskVersion:               "test-datadog-task-version",
	KeyEKSFargateNode:            "test-datadog-eks-fargate-node",
	"custom_tag":                 "test-custom-tag",

	string(semconv127.OSTypeKey):                "test-datadog-os-type",
	string(semconv127.ProcessExecutableNameKey): "test-datadog-process-executable-name",
}

var AllK8sTagsMap = map[string]interface{}{
	KeyArchitecture:              "test-architecture",
	KeyAvailabilityZone:          "test-availability-zone",
	KeyChronosJob:                "test-chronos-job",
	KeyChronosJobOwner:           "test-chronos-job-owner",
	KeyClusterName:               "test-cluster-name",
	KeyContainerID:               "test-container-id",
	KeyContainerName:             "test-container-name",
	KeyDDRemoteConfigID:          "test-dd-remote-config-id",
	KeyDDRemoteConfigRev:         "test-dd-remote-config-rev",
	KeyDisplayContainerName:      "test-display-container-name",
	KeyDockerImage:               "test-docker-image",
	KeyECSClusterName:            "test-ecs-cluster-name",
	KeyECSContainerName:          "test-ecs-container-name",
	KeyEKSFargateNode:            "test-eks-fargate-node",
	KeyEnv:                       "test-env",
	KeyGitCommitSHA:              "test-git-commit-sha",
	KeyGitRepositoryURL:          "test-git-repository-url",
	KeyImageID:                   "test-image-id",
	KeyImageName:                 "test-image-name",
	KeyImageTag:                  "test-image-tag",
	KeyKubeAppComponent:          "test-kube-app-component",
	KeyKubeAppInstance:           "test-kube-app-instance",
	KeyKubeAppManagedBy:          "test-kube-app-managed-by",
	KeyKubeAppName:               "test-kube-app-name",
	KeyKubeAppPartOf:             "test-kube-app-part-of",
	KeyKubeAppVersion:            "test-kube-app-version",
	KeyKubeContainerName:         "test-kube-container-name",
	KeyKubeCronJob:               "test-kube-cronjob",
	KeyKubeDaemonSet:             "test-kube-daemon-set",
	KeyKubeDeployment:            "test-kube-deployment",
	KeyKubeJob:                   "test-kube-job",
	KeyKubeNamespace:             "test-kube-namespace",
	KeyKubeOwnerRefKind:          "test-kube-ownerref-kind",
	KeyKubeOwnerRefName:          "test-kube-ownerref-name",
	KeyKubePriorityClass:         "test-kube-priority-class",
	KeyKubeQOS:                   "test-kube-qos",
	KeyKubeReplicaSet:            "test-kube-replica-set",
	KeyKubeReplicationController: "test-kube-replication-controller",
	KeyKubeService:               "test-kube-service",
	KeyKubeStatefulSet:           "test-kube-stateful-set",
	KeyLanguage:                  "test-language",
	KeyMarathonApp:               "test-marathon-app",
	KeyMesosTask:                 "test-mesos-task",
	KeyNomadDC:                   "test-nomad-dc",
	KeyNomadGroup:                "test-nomad-group",
	KeyNomadJob:                  "test-nomad-job",
	KeyNomadNamespace:            "test-nomad-namespace",
	KeyNomadTask:                 "test-nomad-task",
	KeyOshiftDeployment:          "test-oshift-deployment",
	KeyOshiftDeploymentConfig:    "test-oshift-deployment-config",
	KeyOSName:                    "test-os-name",
	KeyOSVersion:                 "test-os-version",
	KeyPersistentVolumeClaim:     "test-persistentvolumeclaim",
	KeyPodName:                   "test-pod-name",
	KeyPodPhase:                  "test-pod-phase",
	KeyRancherContainer:          "test-rancher-container",
	KeyRancherService:            "test-rancher-service",
	KeyRancherStack:              "test-rancher-stack",
	KeyRegion:                    "test-region",
	KeyService:                   "test-service",
	KeyShortImage:                "test-short-image",
	KeySwarmNamespace:            "test-swarm-namespace",
	KeySwarmService:              "test-swarm-service",
	KeyTaskName:                  "test-task-name",
	KeyTaskFamily:                "test-task-family",
	KeyTaskVersion:               "test-task-version",
	KeyTaskARN:                   "test-task-arn",
	KeyVersion:                   "test-version",
}

var ExhaustiveDatadogAttributesMap = map[string]interface{}{
	"datadog." + KeyEnv:               "test-datadog-env",
	"datadog." + KeyService:           "test-datadog-service",
	"datadog." + KeyVersion:           "test-datadog-version",
	"datadog." + KeyContainerID:       "test-datadog-container-id",
	"datadog." + KeyContainerName:     "test-datadog-container-name",
	"datadog." + KeyImageName:         "test-datadog-image-name",
	"datadog." + KeyImageTag:          "test-datadog-image-tag",
	"datadog." + KeyRuntime:           "test-datadog-runtime",
	"datadog." + KeyCloudProvider:     "test-datadog-cloud-provider",
	"datadog." + KeyRegion:            "test-datadog-region",
	"datadog." + KeyAvailabilityZone:  "test-datadog-zone",
	"datadog." + KeyTaskFamily:        "test-datadog-task-family",
	"datadog." + KeyTaskARN:           "test-datadog-task-arn",
	"datadog." + KeyECSClusterName:    "test-datadog-ecs-cluster-name",
	"datadog." + KeyECSContainerName:  "test-datadog-ecs-container-name",
	"datadog." + KeyKubeContainerName: "test-datadog-kube-container-name",
	"datadog." + KeyKubeClusterName:   "test-datadog-kube-cluster-name",
	"datadog." + KeyKubeDeployment:    "test-datadog-kube-deployment",
	"datadog." + KeyKubeReplicaSet:    "test-datadog-kube-replica-set",
	"datadog." + KeyKubeStatefulSet:   "test-datadog-kube-stateful-set",
	"datadog." + KeyKubeDaemonSet:     "test-datadog-kube-daemon-set",
	"datadog." + KeyKubeJob:           "test-datadog-kube-job",
	"datadog." + KeyKubeCronJob:       "test-datadog-kube-cronjob",
	"datadog." + KeyKubeNamespace:     "test-datadog-kube-namespace",
	"datadog." + KeyPodName:           "test-datadog-pod-name",
	"datadog." + KeyKubeAppName:       "test-datadog-kube-app-name",
	"datadog." + KeyKubeAppInstance:   "test-datadog-kube-app-instance",
	"datadog." + KeyKubeAppVersion:    "test-datadog-kube-app-version",
	"datadog." + KeyKubeAppComponent:  "test-datadog-kube-app-component",
	"datadog." + KeyKubeAppPartOf:     "test-datadog-kube-app-part-of",
	"datadog." + KeyKubeAppManagedBy:  "test-datadog-kube-app-managed-by",

	"datadog." + KeyArchitecture:              "test-datadog-architecture",
	"datadog." + KeyChronosJob:                "test-datadog-chronos-job",
	"datadog." + KeyChronosJobOwner:           "test-datadog-chronos-job-owner",
	"datadog." + KeyClusterName:               "test-datadog-cluster-name",
	"datadog." + KeyDDRemoteConfigID:          "test-datadog-dd-remote-config-id",
	"datadog." + KeyDDRemoteConfigRev:         "test-datadog-dd-remote-config-rev",
	"datadog." + KeyDisplayContainerName:      "test-datadog-display-container-name",
	"datadog." + KeyDockerImage:               "test-datadog-docker-image",
	"datadog." + KeyGitCommitSHA:              "test-datadog-git-commit-sha",
	"datadog." + KeyGitRepositoryURL:          "test-datadog-git-repository-url",
	"datadog." + KeyImageID:                   "test-datadog-image-id",
	"datadog." + KeyKubeOwnerRefKind:          "test-datadog-kube-ownerref-kind",
	"datadog." + KeyKubeOwnerRefName:          "test-datadog-kube-ownerref-name",
	"datadog." + KeyKubePriorityClass:         "test-datadog-kube-priority-class",
	"datadog." + KeyKubeQOS:                   "test-datadog-kube-qos",
	"datadog." + KeyKubeReplicationController: "test-datadog-kube-replication-controller",
	"datadog." + KeyKubeService:               "test-datadog-kube-service",
	"datadog." + KeyLanguage:                  "test-datadog-language",
	"datadog." + KeyMarathonApp:               "test-datadog-marathon-app",
	"datadog." + KeyMesosTask:                 "test-datadog-mesos-task",
	"datadog." + KeyNomadDC:                   "test-datadog-nomad-dc",
	"datadog." + KeyNomadGroup:                "test-datadog-nomad-group",
	"datadog." + KeyNomadJob:                  "test-datadog-nomad-job",
	"datadog." + KeyNomadNamespace:            "test-datadog-nomad-namespace",
	"datadog." + KeyNomadTask:                 "test-datadog-nomad-task",
	"datadog." + KeyOshiftDeployment:          "test-datadog-oshift-deployment",
	"datadog." + KeyOshiftDeploymentConfig:    "test-datadog-oshift-deployment-config",
	"datadog." + KeyOSName:                    "test-datadog-os-name",
	"datadog." + KeyOSVersion:                 "test-datadog-os-version",
	"datadog." + KeyPersistentVolumeClaim:     "test-datadog-persistentvolumeclaim",
	"datadog." + KeyPodPhase:                  "test-datadog-pod-phase",
	"datadog." + KeyRancherContainer:          "test-datadog-rancher-container",
	"datadog." + KeyRancherService:            "test-datadog-rancher-service",
	"datadog." + KeyRancherStack:              "test-datadog-rancher-stack",
	"datadog." + KeyShortImage:                "test-datadog-short-image",
	"datadog." + KeySwarmNamespace:            "test-datadog-swarm-namespace",
	"datadog." + KeySwarmService:              "test-datadog-swarm-service",
	"datadog." + KeyTaskName:                  "test-datadog-task-name",
	"datadog." + KeyTaskVersion:               "test-datadog-task-version",
	"datadog." + KeyEKSFargateNode:            "test-datadog-eks-fargate-node",

	"datadog.container.tag.custom_tag": "test-custom-tag",
	KeyDatadogProcessExecutableName:    "test-datadog-process-executable-name",
	KeyDatadogProcessExecutablePath:    "test-datadog-process-executable-path",
	KeyDatadogProcessCommand:           "test-datadog-process-command",
	KeyDatadogProcessCommandLine:       "test-datadog-process-command-line",
	KeyDatadogProcessPID:               "test-datadog-process-pid",
	KeyDatadogProcessOwner:             "test-datadog-process-owner",
	KeyDatadogOSType:                   "test-datadog-os-type",
}
