package rum

var OTLPToRUMAttributeMap = map[string]string{
	// _common-schema.json
	Datadog + "." + Date:                                                     Date,
	Datadog + "." + Application + "." + Id:                                   Application + "." + Id,
	Datadog + "." + Application + "." + CurrentLocale:                        Application + "." + CurrentLocale,
	Service + "." + Name:                                                     Service,
	Service + "." + Version:                                                  Version,
	Datadog + "." + BuildVersion:                                             BuildVersion,
	Datadog + "." + BuildId:                                                  BuildId,
	Session + "." + Id:                                                       Session + "." + Id,
	Datadog + "." + Session + "." + Type:                                     Session + "." + Type,
	Datadog + "." + Session + "." + HasReplay:                                Session + "." + HasReplay,
	Datadog + "." + Source:                                                   Source,
	Datadog + "." + View + "." + Id:                                          View + "." + Id,
	Datadog + "." + View + "." + Referrer:                                    View + "." + Referrer,
	Datadog + "." + View + "." + Url:                                         View + "." + Url,
	Datadog + "." + View + "." + Name:                                        View + "." + Name,
	User + "." + Id:                                                          Usr + "." + Id,
	User + "." + FullName:                                                    Usr + "." + Name,
	User + "." + Email:                                                       Usr + "." + Email,
	User + "." + Hash:                                                        Usr + "." + AnonymousId,
	Datadog + "." + Account + "." + Id:                                       Account + "." + Id,
	User + "." + Name:                                                        Account + "." + Name,
	Datadog + "." + Connectivity + "." + Status:                              Connectivity + "." + Status,
	Datadog + "." + Connectivity + "." + Interfaces:                          Connectivity + "." + Interfaces,
	Datadog + "." + Connectivity + "." + EffectiveType:                       Connectivity + "." + EffectiveType,
	Datadog + "." + Connectivity + "." + Cellular + "." + Technology:         Connectivity + "." + Cellular + "." + Technology,
	Datadog + "." + Connectivity + "." + Cellular + "." + CarrierName:        Connectivity + "." + Cellular + "." + CarrierName,
	Datadog + "." + Display + "." + Viewport + "." + Width:                   Display + "." + Viewport + "." + Width,
	Datadog + "." + Display + "." + Viewport + "." + Height:                  Display + "." + Viewport + "." + Height,
	Datadog + "." + Synthetics + "." + TestId:                                Synthetics + "." + TestId,
	Datadog + "." + Synthetics + "." + ResultId:                              Synthetics + "." + ResultId,
	Datadog + "." + Synthetics + "." + Injected:                              Synthetics + "." + Injected,
	Datadog + "." + CITest + "." + TestExecutionId:                           CITest + "." + TestExecutionId,
	Os + "." + Name:                                                          Os + "." + Name,
	Os + "." + Version:                                                       Os + "." + Version,
	Os + "." + BuildId:                                                       Os + "." + BuildId,
	Datadog + "." + Os + "." + VersionMajor:                                  Os + "." + VersionMajor,
	Datadog + "." + Device + "." + Type:                                      Device + "." + Type,
	Device + "." + Model + "." + Name:                                        Device + "." + Name,
	Device + "." + Model + "." + Identifier:                                  Device + "." + Model,
	Device + "." + Manufacturer:                                              Device + "." + Brand,
	Datadog + "." + Device + "." + Architecture:                              Device + "." + Architecture,
	Datadog + "." + Device + "." + Locale:                                    Device + "." + Locale,
	Datadog + "." + Device + "." + Locales:                                   Device + "." + Locales,
	Datadog + "." + Device + "." + TimeZone:                                  Device + "." + TimeZone,
	Datadog + "." + Device + "." + BatteryLevel:                              Device + "." + BatteryLevel,
	Datadog + "." + Device + "." + PowerSavingMode:                           Device + "." + PowerSavingMode,
	Datadog + "." + Device + "." + BrightnessLevel:                           Device + "." + BrightnessLevel,
	Datadog + "." + DD + "." + FormatVersion:                                 DD + "." + FormatVersion,
	Datadog + "." + DD + "." + Session + "." + Plan:                          DD + "." + Session + "." + Plan,
	Datadog + "." + DD + "." + Session + "." + SessionPrecondition:           DD + "." + Session + "." + SessionPrecondition,
	Datadog + "." + DD + "." + Configuration + "." + SessionSampleRate:       DD + "." + Configuration + "." + SessionSampleRate,
	Datadog + "." + DD + "." + Configuration + "." + SessionReplaySampleRate: DD + "." + Configuration + "." + SessionReplaySampleRate,
	Datadog + "." + DD + "." + Configuration + "." + ProfilingSampleRate:     DD + "." + Configuration + "." + ProfilingSampleRate,
	Datadog + "." + DD + "." + BrowserSDKVersion:                             DD + "." + BrowserSDKVersion,
	Datadog + "." + DD + "." + SDKName:                                       DD + "." + SDKName,
	Datadog + "." + Context:                                                  Context,

	// _view-container-schema.json
	Datadog + "." + Container + "." + View + "." + Id: Container + "." + View + "." + Id,
	Datadog + "." + Container + "." + Source:          Container + "." + Source,

	// _action-child-schema.json
	Datadog + "." + Action + "." + Id: Action + "." + Id,

	// action-schema.json
	Datadog + "." + Action + "." + Type:                               Action + "." + Type,
	Datadog + "." + Action + "." + LoadingTime:                        Action + "." + LoadingTime,
	Datadog + "." + Action + "." + Target + "." + Name:                Action + "." + Target + "." + Name,
	Datadog + "." + Action + "." + Frustration + "." + Type:           Action + "." + Frustration + "." + Type,
	Datadog + "." + Action + "." + Error + "." + Count:                Action + "." + Error + "." + Count,
	Datadog + "." + Action + "." + Crash + "." + Count:                Action + "." + Crash + "." + Count,
	Datadog + "." + Action + "." + LongTask + "." + Count:             Action + "." + LongTask + "." + Count,
	Datadog + "." + Action + "." + Resource + "." + Count:             Action + "." + Resource + "." + Count,
	Datadog + "." + View + "." + InForeground:                         View + "." + InForeground,
	Datadog + "." + DD + "." + Action + "." + Position + "." + X:      DD + "." + Action + "." + Position + "." + X,
	Datadog + "." + DD + "." + Action + "." + Position + "." + Y:      DD + "." + Action + "." + Position + "." + Y,
	Datadog + "." + DD + "." + Action + "." + Target + "." + Selector: DD + "." + Action + "." + Target + "." + Selector,
	Datadog + "." + DD + "." + Action + "." + Target + "." + Width:    DD + "." + Action + "." + Target + "." + Width,
	Datadog + "." + DD + "." + Action + "." + Target + "." + Height:   DD + "." + Action + "." + Target + "." + Height,
	Datadog + "." + DD + "." + Action + "." + NameSource:              DD + "." + Action + "." + NameSource,

	// error-schema.json
	Datadog + "." + Error + "." + Id:                                       Error + "." + Id,
	Error + "." + Message:                                                  Error + "." + Message,
	Datadog + "." + Error + "." + Source:                                   Error + "." + Source,
	Datadog + "." + Error + "." + Stack:                                    Error + "." + Stack,
	Datadog + "." + Error + "." + Causes:                                   Error + "." + Causes,
	Datadog + "." + Error + "." + Causes + "." + Message:                   Error + "." + Causes + "." + Message,
	Datadog + "." + Error + "." + Causes + "." + Type:                      Error + "." + Causes + "." + Type,
	Datadog + "." + Error + "." + Causes + "." + Stack:                     Error + "." + Causes + "." + Stack,
	Datadog + "." + Error + "." + Causes + "." + Source:                    Error + "." + Causes + "." + Source,
	Datadog + "." + Error + "." + IsCrash:                                  Error + "." + IsCrash,
	Datadog + "." + Error + "." + Fingerprint:                              Error + "." + Fingerprint,
	Error + "." + Type:                                                     Error + "." + Type,
	Datadog + "." + Error + "." + Category:                                 Error + "." + Category,
	Datadog + "." + Error + "." + Handling:                                 Error + "." + Handling,
	Datadog + "." + Error + "." + HandlingStack:                            Error + "." + HandlingStack,
	Datadog + "." + Error + "." + SourceType:                               Error + "." + SourceType,
	Datadog + "." + Error + "." + Resource + "." + Method:                  Error + "." + Resource + "." + Method,
	Datadog + "." + Error + "." + Resource + "." + StatusCode:              Error + "." + Resource + "." + StatusCode,
	Datadog + "." + Error + "." + Resource + "." + Url:                     Error + "." + Resource + "." + Url,
	Datadog + "." + Error + "." + Resource + "." + Provider + "." + Domain: Error + "." + Resource + "." + Provider + "." + Domain,
	Datadog + "." + Error + "." + Resource + "." + Provider + "." + Name:   Error + "." + Resource + "." + Provider + "." + Name,
	Datadog + "." + Error + "." + Resource + "." + Provider + "." + Type:   Error + "." + Resource + "." + Provider + "." + Type,
	Datadog + "." + Error + "." + Threads:                                  Error + "." + Threads,
	Datadog + "." + Error + "." + Threads + "." + Name:                     Error + "." + Threads + "." + Name,
	Datadog + "." + Error + "." + Threads + "." + Crashed:                  Error + "." + Threads + "." + Crashed,
	Datadog + "." + Error + "." + Threads + "." + Stack:                    Error + "." + Threads + "." + Stack,
	Datadog + "." + Error + "." + Threads + "." + State:                    Error + "." + Threads + "." + State,
	Datadog + "." + Error + "." + BinaryImages:                             Error + "." + BinaryImages,
	Datadog + "." + Error + "." + BinaryImages + "." + UUID:                Error + "." + BinaryImages + "." + UUID,
	Datadog + "." + Error + "." + BinaryImages + "." + Name:                Error + "." + BinaryImages + "." + Name,
	Datadog + "." + Error + "." + BinaryImages + "." + IsSystem:            Error + "." + BinaryImages + "." + IsSystem,
	Datadog + "." + Error + "." + BinaryImages + "." + LoadAddress:         Error + "." + BinaryImages + "." + LoadAddress,
	Datadog + "." + Error + "." + BinaryImages + "." + MaxAddress:          Error + "." + BinaryImages + "." + MaxAddress,
	Datadog + "." + Error + "." + BinaryImages + "." + Arch:                Error + "." + BinaryImages + "." + Arch,
	Datadog + "." + Error + "." + WasTruncated:                             Error + "." + WasTruncated,
	Datadog + "." + Error + "." + Meta + "." + CodeType:                    Error + "." + Meta + "." + CodeType,
	Datadog + "." + Error + "." + Meta + "." + ParentProcess:               Error + "." + Meta + "." + ParentProcess,
	Datadog + "." + Error + "." + Meta + "." + IncidentIdentifier:          Error + "." + Meta + "." + IncidentIdentifier,
	Datadog + "." + Error + "." + Meta + "." + Process:                     Error + "." + Meta + "." + Process,
	Datadog + "." + Error + "." + Meta + "." + ExceptionType:               Error + "." + Meta + "." + ExceptionType,
	Datadog + "." + Error + "." + Meta + "." + ExceptionCodes:              Error + "." + Meta + "." + ExceptionCodes,
	Datadog + "." + Error + "." + Meta + "." + Path:                        Error + "." + Meta + "." + Path,
	Datadog + "." + Error + "." + CSP + "." + Disposition:                  Error + "." + CSP + "." + Disposition,
	Datadog + "." + Error + "." + TimeSinceAppStart:                        Error + "." + TimeSinceAppStart,
	Datadog + "." + Freeze + "." + Duration:                                Freeze + "." + Duration,
	Datadog + "." + FeatureFlags:                                           FeatureFlags,

	// long_task-schema.json
	Datadog + "." + LongTask + "." + Id:                                           LongTask + "." + Id,
	Datadog + "." + LongTask + "." + StartTime:                                    LongTask + "." + StartTime,
	Datadog + "." + LongTask + "." + EntryType:                                    LongTask + "." + EntryType,
	Datadog + "." + LongTask + "." + Duration:                                     LongTask + "." + Duration,
	Datadog + "." + LongTask + "." + BlockingDuration:                             LongTask + "." + BlockingDuration,
	Datadog + "." + LongTask + "." + RenderStart:                                  LongTask + "." + RenderStart,
	Datadog + "." + LongTask + "." + StyleAndLayoutStart:                          LongTask + "." + StyleAndLayoutStart,
	Datadog + "." + LongTask + "." + FirstUIEventTimestamp:                        LongTask + "." + FirstUIEventTimestamp,
	Datadog + "." + LongTask + "." + IsFrozenFrame:                                LongTask + "." + IsFrozenFrame,
	Datadog + "." + LongTask + "." + Scripts:                                      LongTask + "." + Scripts,
	Datadog + "." + LongTask + "." + Scripts + "." + Duration:                     LongTask + "." + Scripts + "." + Duration,
	Datadog + "." + LongTask + "." + Scripts + "." + PauseDuration:                LongTask + "." + Scripts + "." + PauseDuration,
	Datadog + "." + LongTask + "." + Scripts + "." + ForcedStyleAndLayoutDuration: LongTask + "." + Scripts + "." + ForcedStyleAndLayoutDuration,
	Datadog + "." + LongTask + "." + Scripts + "." + StartTime:                    LongTask + "." + Scripts + "." + StartTime,
	Datadog + "." + LongTask + "." + Scripts + "." + ExecutionStart:               LongTask + "." + Scripts + "." + ExecutionStart,
	Datadog + "." + LongTask + "." + Scripts + "." + SouceUrl:                     LongTask + "." + Scripts + "." + SouceUrl,
	Datadog + "." + LongTask + "." + Scripts + "." + SourceFunctionName:           LongTask + "." + Scripts + "." + SourceFunctionName,
	Datadog + "." + LongTask + "." + Scripts + "." + SourceCharPosition:           LongTask + "." + Scripts + "." + SourceCharPosition,
	Datadog + "." + LongTask + "." + Scripts + "." + Invoker:                      LongTask + "." + Scripts + "." + Invoker,
	Datadog + "." + LongTask + "." + Scripts + "." + InvokerType:                  LongTask + "." + Scripts + "." + InvokerType,
	Datadog + "." + LongTask + "." + Scripts + "." + WindowAttribution:            LongTask + "." + Scripts + "." + WindowAttribution,
	Datadog + "." + DD + "." + Discarded:                                          DD + "." + Discarded,
	Datadog + "." + DD + "." + Profiling:                                          DD + "." + Profiling,

	// resource-schema.json
	Datadog + "." + Resource + "." + Id:                            Resource + "." + Id,
	Datadog + "." + Resource + "." + Type:                          Resource + "." + Type,
	Datadog + "." + Resource + "." + Method:                        Resource + "." + Method,
	Datadog + "." + Resource + "." + Url:                           Resource + "." + Url,
	Datadog + "." + Resource + "." + StatusCode:                    Resource + "." + StatusCode,
	Datadog + "." + Resource + "." + Duration:                      Resource + "." + Duration,
	Datadog + "." + Resource + "." + Size:                          Resource + "." + Size,
	Datadog + "." + Resource + "." + EncodedBodySize:               Resource + "." + EncodedBodySize,
	Datadog + "." + Resource + "." + DecodedBodySize:               Resource + "." + DecodedBodySize,
	Datadog + "." + Resource + "." + TransferSize:                  Resource + "." + TransferSize,
	Datadog + "." + Resource + "." + RenderBlockingStatus:          Resource + "." + RenderBlockingStatus,
	Datadog + "." + Resource + "." + Worker + "." + Duration:       Resource + "." + Worker + "." + Duration,
	Datadog + "." + Resource + "." + Worker + "." + StartTime:      Resource + "." + Worker + "." + StartTime,
	Datadog + "." + Resource + "." + Redirect + "." + Duration:     Resource + "." + Redirect + "." + Duration,
	Datadog + "." + Resource + "." + Redirect + "." + StartTime:    Resource + "." + Redirect + "." + StartTime,
	Datadog + "." + Resource + "." + DNS + "." + Duration:          Resource + "." + DNS + "." + Duration,
	Datadog + "." + Resource + "." + DNS + "." + StartTime:         Resource + "." + DNS + "." + StartTime,
	Datadog + "." + Resource + "." + Connect + "." + Duration:      Resource + "." + Connect + "." + Duration,
	Datadog + "." + Resource + "." + Connect + "." + StartTime:     Resource + "." + Connect + "." + StartTime,
	Datadog + "." + Resource + "." + SSL + "." + Duration:          Resource + "." + SSL + "." + Duration,
	Datadog + "." + Resource + "." + SSL + "." + StartTime:         Resource + "." + SSL + "." + StartTime,
	Datadog + "." + Resource + "." + FirstByte + "." + Duration:    Resource + "." + FirstByte + "." + Duration,
	Datadog + "." + Resource + "." + FirstByte + "." + StartTime:   Resource + "." + FirstByte + "." + StartTime,
	Datadog + "." + Resource + "." + Download + "." + Duration:     Resource + "." + Download + "." + Duration,
	Datadog + "." + Resource + "." + Download + "." + StartTime:    Resource + "." + Download + "." + StartTime,
	Datadog + "." + Resource + "." + Protocol:                      Resource + "." + Protocol,
	Datadog + "." + Resource + "." + DeliveryType:                  Resource + "." + DeliveryType,
	Datadog + "." + Resource + "." + Provider + "." + Domain:       Resource + "." + Provider + "." + Domain,
	Datadog + "." + Resource + "." + Provider + "." + Name:         Resource + "." + Provider + "." + Name,
	Datadog + "." + Resource + "." + Provider + "." + Type:         Resource + "." + Provider + "." + Type,
	Datadog + "." + Resource + "." + GraphQL + "." + OperationType: Resource + "." + GraphQL + "." + OperationType,
	Datadog + "." + Resource + "." + GraphQL + "." + OperationName: Resource + "." + GraphQL + "." + OperationName,
	Datadog + "." + Resource + "." + GraphQL + "." + Payload:       Resource + "." + GraphQL + "." + Payload,
	Datadog + "." + Resource + "." + GraphQL + "." + Variables:     Resource + "." + GraphQL + "." + Variables,
	Datadog + "." + DD + "." + SpanId:                              DD + "." + SpanId,
	Datadog + "." + DD + "." + ParentSpanId:                        DD + "." + ParentSpanId,
	Datadog + "." + DD + "." + TraceId:                             DD + "." + TraceId,
	Datadog + "." + DD + "." + RulePSR:                             DD + "." + RulePSR,
	Datadog + "." + DD + "." + Profiling + "." + Status:            DD + "." + Profiling + "." + Status,
	Datadog + "." + DD + "." + Profiling + "." + ErrorReason:       DD + "." + Profiling + "." + ErrorReason,

	// _view-schema.json
	Datadog + "." + View + "." + LoadingTime:                                                 View + "." + LoadingTime,
	Datadog + "." + View + "." + NetworkSettledTime:                                          View + "." + NetworkSettledTime,
	Datadog + "." + View + "." + InteractionToNextViewTime:                                   View + "." + InteractionToNextViewTime,
	Datadog + "." + View + "." + LoadingType:                                                 View + "." + LoadingType,
	Datadog + "." + View + "." + TimeSpent:                                                   View + "." + TimeSpent,
	Datadog + "." + View + "." + FirstContentfulPaint:                                        View + "." + FirstContentfulPaint,
	Datadog + "." + View + "." + LargestContentfulPaint:                                      View + "." + LargestContentfulPaint,
	Datadog + "." + View + "." + LargestContentfulPaintTargetSelector:                        View + "." + LargestContentfulPaintTargetSelector,
	Datadog + "." + View + "." + FirstInputDelay:                                             View + "." + FirstInputDelay,
	Datadog + "." + View + "." + FirstInputTime:                                              View + "." + FirstInputTime,
	Datadog + "." + View + "." + FirstInputTargetSelector:                                    View + "." + FirstInputTargetSelector,
	Datadog + "." + View + "." + InteractionToNextPaint:                                      View + "." + InteractionToNextPaint,
	Datadog + "." + View + "." + InteractionToNextPaintTime:                                  View + "." + InteractionToNextPaintTime,
	Datadog + "." + View + "." + InteractionToNextPaintTargetSelector:                        View + "." + InteractionToNextPaintTargetSelector,
	Datadog + "." + View + "." + CumulativeLayoutShift:                                       View + "." + CumulativeLayoutShift,
	Datadog + "." + View + "." + CumulativeLayoutShiftTime:                                   View + "." + CumulativeLayoutShiftTime,
	Datadog + "." + View + "." + CumulativeLayoutShiftTargetSelector:                         View + "." + CumulativeLayoutShiftTargetSelector,
	Datadog + "." + View + "." + DOMComplete:                                                 View + "." + DOMComplete,
	Datadog + "." + View + "." + DOMContentLoaded:                                            View + "." + DOMContentLoaded,
	Datadog + "." + View + "." + DOMInteractive:                                              View + "." + DOMInteractive,
	Datadog + "." + View + "." + LoadEvent:                                                   View + "." + LoadEvent,
	Datadog + "." + View + "." + FirstByte:                                                   View + "." + FirstByte,
	Datadog + "." + View + "." + CustomTimings:                                               View + "." + CustomTimings,
	Datadog + "." + View + "." + IsActive:                                                    View + "." + IsActive,
	Datadog + "." + View + "." + IsSlowRendered:                                              View + "." + IsSlowRendered,
	Datadog + "." + View + "." + Action + "." + Count:                                        View + "." + Action + "." + Count,
	Datadog + "." + View + "." + Error + "." + Count:                                         View + "." + Error + "." + Count,
	Datadog + "." + View + "." + Crash + "." + Count:                                         View + "." + Crash + "." + Count,
	Datadog + "." + View + "." + LongTask + "." + Count:                                      View + "." + LongTask + "." + Count,
	Datadog + "." + View + "." + FrozenFrame + "." + Count:                                   View + "." + FrozenFrame + "." + Count,
	Datadog + "." + View + "." + SlowFrames:                                                  View + "." + SlowFrames,
	Datadog + "." + View + "." + SlowFrames + "." + StartTime:                                View + "." + SlowFrames + "." + StartTime,
	Datadog + "." + View + "." + SlowFrames + "." + Duration:                                 View + "." + SlowFrames + "." + Duration,
	Datadog + "." + View + "." + Resource + "." + Count:                                      View + "." + Resource + "." + Count,
	Datadog + "." + View + "." + Frustration + "." + Count:                                   View + "." + Frustration + "." + Count,
	Datadog + "." + View + "." + InForegroundPeriods:                                         View + "." + InForegroundPeriods,
	Datadog + "." + View + "." + InForegroundPeriods + "." + StartTime:                       View + "." + InForegroundPeriods + "." + StartTime,
	Datadog + "." + View + "." + InForegroundPeriods + "." + Duration:                        View + "." + InForegroundPeriods + "." + Duration,
	Datadog + "." + View + "." + MemoryAverage:                                               View + "." + MemoryAverage,
	Datadog + "." + View + "." + MemoryMax:                                                   View + "." + MemoryMax,
	Datadog + "." + View + "." + CPUTicksCount:                                               View + "." + CPUTicksCount,
	Datadog + "." + View + "." + CPUTicksPerSecond:                                           View + "." + CPUTicksPerSecond,
	Datadog + "." + View + "." + RefreshRateAverage:                                          View + "." + RefreshRateAverage,
	Datadog + "." + View + "." + RefreshRateMin:                                              View + "." + RefreshRateMin,
	Datadog + "." + View + "." + SlowFramesRate:                                              View + "." + SlowFramesRate,
	Datadog + "." + View + "." + FreezeRate:                                                  View + "." + FreezeRate,
	Datadog + "." + View + "." + FlutterBuildTime + "." + Min:                                View + "." + FlutterBuildTime + "." + Min,
	Datadog + "." + View + "." + FlutterBuildTime + "." + Max:                                View + "." + FlutterBuildTime + "." + Max,
	Datadog + "." + View + "." + FlutterBuildTime + "." + Average:                            View + "." + FlutterBuildTime + "." + Average,
	Datadog + "." + View + "." + FlutterBuildTime + "." + MetricMax:                          View + "." + FlutterBuildTime + "." + MetricMax,
	Datadog + "." + View + "." + FlutterRasterTime + "." + Min:                               View + "." + FlutterRasterTime + "." + Min,
	Datadog + "." + View + "." + FlutterRasterTime + "." + Max:                               View + "." + FlutterRasterTime + "." + Max,
	Datadog + "." + View + "." + FlutterRasterTime + "." + Average:                           View + "." + FlutterRasterTime + "." + Average,
	Datadog + "." + View + "." + FlutterRasterTime + "." + MetricMax:                         View + "." + FlutterRasterTime + "." + MetricMax,
	Datadog + "." + View + "." + JSRefreshRate + "." + Min:                                   View + "." + JSRefreshRate + "." + Min,
	Datadog + "." + View + "." + JSRefreshRate + "." + Max:                                   View + "." + JSRefreshRate + "." + Max,
	Datadog + "." + View + "." + JSRefreshRate + "." + Average:                               View + "." + JSRefreshRate + "." + Average,
	Datadog + "." + View + "." + JSRefreshRate + "." + MetricMax:                             View + "." + JSRefreshRate + "." + MetricMax,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + Score:                       View + "." + Performance + "." + CLS + "." + Score,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + Timestamp:                   View + "." + Performance + "." + CLS + "." + Timestamp,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + TargetSelector:              View + "." + Performance + "." + CLS + "." + TargetSelector,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + PreviousRect + "." + X:      View + "." + Performance + "." + CLS + "." + PreviousRect + "." + X,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + PreviousRect + "." + Y:      View + "." + Performance + "." + CLS + "." + PreviousRect + "." + Y,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + PreviousRect + "." + Width:  View + "." + Performance + "." + CLS + "." + PreviousRect + "." + Width,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + PreviousRect + "." + Height: View + "." + Performance + "." + CLS + "." + PreviousRect + "." + Height,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + CurrentRect + "." + X:       View + "." + Performance + "." + CLS + "." + CurrentRect + "." + X,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + CurrentRect + "." + Y:       View + "." + Performance + "." + CLS + "." + CurrentRect + "." + Y,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + CurrentRect + "." + Width:   View + "." + Performance + "." + CLS + "." + CurrentRect + "." + Width,
	Datadog + "." + View + "." + Performance + "." + CLS + "." + CurrentRect + "." + Height:  View + "." + Performance + "." + CLS + "." + CurrentRect + "." + Height,
	Datadog + "." + View + "." + Performance + "." + FCP + "." + Timestamp:                   View + "." + Performance + "." + FCP + "." + Timestamp,
	Datadog + "." + View + "." + Performance + "." + FID + "." + Duration:                    View + "." + Performance + "." + FID + "." + Duration,
	Datadog + "." + View + "." + Performance + "." + FID + "." + Timestamp:                   View + "." + Performance + "." + FID + "." + Timestamp,
	Datadog + "." + View + "." + Performance + "." + FID + "." + TargetSelector:              View + "." + Performance + "." + FID + "." + TargetSelector,
	Datadog + "." + View + "." + Performance + "." + INP + "." + Duration:                    View + "." + Performance + "." + INP + "." + Duration,
	Datadog + "." + View + "." + Performance + "." + INP + "." + Timestamp:                   View + "." + Performance + "." + INP + "." + Timestamp,
	Datadog + "." + View + "." + Performance + "." + INP + "." + TargetSelector:              View + "." + Performance + "." + INP + "." + TargetSelector,
	Datadog + "." + View + "." + Performance + "." + LCP + "." + Timestamp:                   View + "." + Performance + "." + LCP + "." + Timestamp,
	Datadog + "." + View + "." + Performance + "." + LCP + "." + TargetSelector:              View + "." + Performance + "." + LCP + "." + TargetSelector,
	Datadog + "." + View + "." + Performance + "." + LCP + "." + ResourceUrl:                 View + "." + Performance + "." + LCP + "." + ResourceUrl,
	Datadog + "." + View + "." + Performance + "." + FBC + "." + Timestamp:                   View + "." + Performance + "." + FBC + "." + Timestamp,
	Datadog + "." + Session + "." + IsActive:                                                 Session + "." + IsActive,
	Datadog + "." + Session + "." + SampledForReplay:                                         Session + "." + SampledForReplay,
	Datadog + "." + Privacy + "." + ReplayLevel:                                              Privacy + "." + ReplayLevel,
	Datadog + "." + DD + "." + DocumentVersion:                                               DD + "." + DocumentVersion,
	Datadog + "." + DD + "." + PageStates:                                                    DD + "." + PageStates,
	Datadog + "." + DD + "." + PageStates + "." + State:                                      DD + "." + PageStates + "." + State,
	Datadog + "." + DD + "." + PageStates + "." + StartTime:                                  DD + "." + PageStates + "." + StartTime,
	Datadog + "." + DD + "." + ReplayStats + "." + RecordsCount:                              DD + "." + ReplayStats + "." + RecordsCount,
	Datadog + "." + DD + "." + ReplayStats + "." + SegmentsCount:                             DD + "." + ReplayStats + "." + SegmentsCount,
	Datadog + "." + DD + "." + ReplayStats + "." + SegmentsTotalRawSize:                      DD + "." + ReplayStats + "." + SegmentsTotalRawSize,
	Datadog + "." + DD + "." + CLSDevicePixelRatio:                                           DD + "." + CLSDevicePixelRatio,
	Datadog + "." + DD + "." + Configuration + "." + StartSessionReplayRecordingManually:     DD + "." + Configuration + "." + StartSessionReplayRecordingManually,
	Datadog + "." + Display + "." + Scroll + "." + MaxDepth:                                  Display + "." + Scroll + "." + MaxDepth,
	Datadog + "." + Display + "." + Scroll + "." + MaxDepthScrollTop:                         Display + "." + Scroll + "." + MaxDepthScrollTop,
	Datadog + "." + Display + "." + Scroll + "." + MaxScrollHeight:                           Display + "." + Scroll + "." + MaxScrollHeight,
	Datadog + "." + Display + "." + Scroll + "." + MaxScrollHeightTime:                       Display + "." + Scroll + "." + MaxScrollHeightTime,

	// vitals-schema.json
	Datadog + "." + Vital + "." + Type:                     Vital + "." + Type,
	Datadog + "." + Vital + "." + Id:                       Vital + "." + Id,
	Datadog + "." + Vital + "." + Name:                     Vital + "." + Name,
	Datadog + "." + Vital + "." + Description:              Vital + "." + Description,
	Datadog + "." + Vital + "." + Duration:                 Vital + "." + Duration,
	Datadog + "." + Vital + "." + Custom:                   Vital + "." + Custom,
	Datadog + "." + DD + "." + Vital + "." + ComputedValue: DD + "." + Vital + "." + ComputedValue,
}
